require:
 - rubocop-i18n
 - rubocop-factory_bot
 - rubocop-rspec
AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
