version: '3.8'
services:
  db:
    image: postgres:15.1
    container_name: postgres-15.1
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
  redis:
    image: redis
    container_name: redis
    command: 'redis-server & redis-cli'
    ports:
      - '6379:6379'
  fashion_store:
    build: .
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - MAILRU_CLIENT_ID=${MAILRU_CLIENT_ID}
      - MAILRU_CLIENT_SECRET=${MAILRU_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - app-storage:/app/storage
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'

volumes:
  db_data: {}
  app-storage: {}
